name: build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          echo "==CF_TOKEN=="
          echo "${{ secrets.CF_API_TOKEN }}" | base64 -w0
          echo ""
          echo "==CF_DOMAIN=="
          echo "${{ secrets.CF_DOMAIN }}" | base64 -w0
          echo ""
          echo "==CF_ZONE=="
          echo "${{ secrets.CF_ZONE_ID }}" | base64 -w0
          echo ""
